[package]
name = "heic_transcoder"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libheif-rs = { version = "2.7", features = ["embedded-libheif"] }
image = { version = "0.25", default-features = false, features = ["jpeg"] }

[profile.release]
lto = true
opt-level = 3
strip = "symbols"

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-arch", "-C", "link-arg=x86_64"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-arch", "-C", "link-arg=arm64"]
